runtime: python3

# the following codes was commented out since they will incur charges, 
# if you want to try the face detection function, please use those codes

#env: flex
#entrypoint: gunicorn -b :$PORT main:app

#runtime_config:
#  python_version: 3

#env_variables:
#  CLOUD_STORAGE_BUCKET: delivery-304123
